# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: setup safe direcotry
        run: git config --global --add safe.directory /__w/GBI-Tutorium-Folien/GBI-Tutorium-Folien

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40

      - name: update package list
        run: apt-get update
      - name: Install ipe
        run: apt install ipe -y

      - name: Convert ipe files to pdf
        shell: bash
        run: |
          files=(${{ steps.changed-files.outputs.all_changed_files }})
          for file in "${files[@]}"; do
            file="${file@E}"
            if [[ ${file##*.} == "ipe" && ${file} != "00-Preset.ipe" ]]
            then
              ipetoipe -pdf ${file} ${file%.*}.pdf
            fi
          done

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: Slides
          path: "*.pdf"
