# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: 
      image: texlive/texlive:latest
      options: --user root

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}
      - name: Get changed files
        id: changed-files
        run: |
              echo $(git status)
      #       if ${{ github.event_name == 'pull_request' }}; then
      #           echo "changed_files=$(git diff --name-only -r HEAD^1 HEAD | xargs)" >> $GITHUB_OUTPUT
      #       else
      #           echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT
      #       fi
      # - name: List changed files
      #   run: |
      #       for file in ${{ steps.changed-files.outputs.changed_files }}; do
      #           echo "$file was changed"
      #       done


      # Runs a single command using the runners shell
      # - name: update package list
      #   run: apt-get update
      # - name: Install ipe
      #   run: apt install ipe -y

      # - name: Convert to pdf
      #   run: ipetoipe -pdf 01-Orga-Mengenlehre.ipe 01-Orga-Mengenlehre.pdf

      # - name: Upload binary
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: PDFs
      #     path: "*.pdf"
